Name: ucenter.rpc
ListenOn: 0.0.0.0:8081
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: ucenter.rpc
Mysql:
  DataSource: root:root@tcp(127.0.0.1:3309)/zero_mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
CacheRedis:
  - Host: 127.0.0.1:6379
    Type: node
Captcha:
  vid: 668fa929d3784602950e9511
  key: 4f311bc7c7374d64bb3443ebf5c10b52
JWT:
  AccessSecret: "MacReeee@github.com"
  AccessExpire: 604800
MarketRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: market.rpc
  NonBlock: true
Kafka:
  Addr: localhost:9092
  WriteCap: 100
  ReadCap: 100
  ConsumerGroup: "ucenter-consumer"
ExchangeRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: exchange.rpc
  NonBlock: true
Bitcoin:
  Address: "http://127.0.0.1:18332"